alter table public.admin_users enable row level security;
drop policy if exists "Admins can read own admin row" on public.admin_users;
create policy "Admins can read own admin row" on public.admin_users for select to authenticated using(user_id=auth.uid());
insert into storage.buckets(id,name,public) values('product-images','product-images',true) on conflict(id) do update set public=true;
drop policy if exists "Public can view product images" on storage.objects;
create policy "Public can view product images" on storage.objects for select using(bucket_id='product-images');
drop policy if exists "Admins can upload product images" on storage.objects;
create policy "Admins can upload product images" on storage.objects for insert to authenticated with check(bucket_id='product-images' and exists(select 1 from public.admin_users where user_id=auth.uid()));
drop policy if exists "Admins can update product images" on storage.objects;
create policy "Admins can update product images" on storage.objects for update to authenticated using(bucket_id='product-images' and exists(select 1 from public.admin_users where user_id=auth.uid())) with check(bucket_id='product-images' and exists(select 1 from public.admin_users where user_id=auth.uid()));
drop policy if exists "Admins can delete product images" on storage.objects;
create policy "Admins can delete product images" on storage.objects for delete to authenticated using(bucket_id='product-images' and exists(select 1 from public.admin_users where user_id=auth.uid()));
